//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureLoginWebApp.SecureLoginService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/SecureLoginService.Model")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/SecureLoginService.Model")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureLoginWebApp.SecureLoginService.Types TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureLoginWebApp.SecureLoginService.Types Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Types", Namespace="http://schemas.datacontract.org/2004/07/SecureLoginService.Model")]
    public enum Types : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CorrectLogin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IncorrectLogin = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountExist = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountCreated = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecureLoginService.ISecureLoginService")]
    public interface ISecureLoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecureLoginService/Login", ReplyAction="http://tempuri.org/ISecureLoginService/LoginResponse")]
        SecureLoginWebApp.SecureLoginService.Response Login(SecureLoginWebApp.SecureLoginService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecureLoginService/Login", ReplyAction="http://tempuri.org/ISecureLoginService/LoginResponse")]
        System.Threading.Tasks.Task<SecureLoginWebApp.SecureLoginService.Response> LoginAsync(SecureLoginWebApp.SecureLoginService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecureLoginService/AddUser", ReplyAction="http://tempuri.org/ISecureLoginService/AddUserResponse")]
        SecureLoginWebApp.SecureLoginService.Response AddUser(SecureLoginWebApp.SecureLoginService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecureLoginService/AddUser", ReplyAction="http://tempuri.org/ISecureLoginService/AddUserResponse")]
        System.Threading.Tasks.Task<SecureLoginWebApp.SecureLoginService.Response> AddUserAsync(SecureLoginWebApp.SecureLoginService.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecureLoginServiceChannel : SecureLoginWebApp.SecureLoginService.ISecureLoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecureLoginServiceClient : System.ServiceModel.ClientBase<SecureLoginWebApp.SecureLoginService.ISecureLoginService>, SecureLoginWebApp.SecureLoginService.ISecureLoginService {
        
        public SecureLoginServiceClient() {
        }
        
        public SecureLoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecureLoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecureLoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecureLoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SecureLoginWebApp.SecureLoginService.Response Login(SecureLoginWebApp.SecureLoginService.User user) {
            return base.Channel.Login(user);
        }
        
        public System.Threading.Tasks.Task<SecureLoginWebApp.SecureLoginService.Response> LoginAsync(SecureLoginWebApp.SecureLoginService.User user) {
            return base.Channel.LoginAsync(user);
        }
        
        public SecureLoginWebApp.SecureLoginService.Response AddUser(SecureLoginWebApp.SecureLoginService.User user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<SecureLoginWebApp.SecureLoginService.Response> AddUserAsync(SecureLoginWebApp.SecureLoginService.User user) {
            return base.Channel.AddUserAsync(user);
        }
    }
}
